version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Backend.Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - QDRANT_HOST=${QDRANT_HOST}
      - QDRANT_PORT=${QDRANT_PORT}
      - QDRANT_COLLECTION_NAME=${QDRANT_COLLECTION_NAME}
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    depends_on:
      - qdrant
    restart: unless-stopped
    networks:
      - backend-network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant_data
    environment:
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    restart: unless-stopped
    networks:
      - backend-network

volumes:
  qdrant_data:

networks:
  backend-network:
    driver: bridge