openapi: 3.0.0
info:
  title: RAG Agent API
  description: API for the RAG Agent that answers user queries using retrieved document chunks
  version: 1.0.0
  contact:
    name: RAG Agent Development Team

servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.example.com
    description: Production server

paths:
  /v1/agent/query:
    post:
      summary: Query the RAG Agent
      description: Submit a natural language query to the RAG agent and receive a grounded response
      operationId: queryAgent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgentQueryRequest'
      responses:
        '200':
          description: Successful response from the agent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentQueryResponse'
        '400':
          description: Invalid query parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /v1/agent/health:
    get:
      summary: Health check for the agent service
      description: Check if the RAG agent service is running and healthy
      operationId: agentHealth
      responses:
        '200':
          description: Agent service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
        '500':
          description: Agent service is unhealthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /v1/agent/status:
    get:
      summary: Get agent status and statistics
      description: Retrieve current status and performance metrics for the agent
      operationId: agentStatus
      responses:
        '200':
          description: Agent status information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentStatusResponse'
        '500':
          description: Error retrieving agent status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    AgentQueryRequest:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          description: The natural language query to process
          example: "What is artificial intelligence?"
        include_citations:
          type: boolean
          description: Whether to include source citations in the response
          default: true
        max_chunks:
          type: integer
          description: Maximum number of chunks to retrieve
          default: 5
          minimum: 1
          maximum: 20
        similarity_threshold:
          type: number
          description: Minimum similarity score for retrieved chunks
          default: 0.7
          minimum: 0.0
          maximum: 1.0

    AgentQueryResponse:
      type: object
      required:
        - response_id
        - response
        - citations
        - retrieved_chunks_count
        - processing_time_ms
        - confidence
      properties:
        response_id:
          type: string
          description: Unique identifier for this response
          example: "resp_1234567890"
        response:
          type: string
          description: The agent's response to the query
          example: "Artificial intelligence (AI) is intelligence demonstrated by machines..."
        citations:
          type: array
          description: List of sources cited in the response
          items:
            $ref: '#/components/schemas/Citation'
        retrieved_chunks_count:
          type: integer
          description: Number of document chunks retrieved for the response
          example: 3
        processing_time_ms:
          type: integer
          description: Time taken to process the query in milliseconds
          example: 1250
        confidence:
          type: number
          description: Confidence score for the response
          minimum: 0.0
          maximum: 1.0
          example: 0.92

    Citation:
      type: object
      required:
        - source_url
        - document_id
        - similarity_score
      properties:
        source_url:
          type: string
          description: URL of the source document
          format: uri
          example: "https://example.com/ai-textbook"
        document_id:
          type: string
          description: ID of the document
          example: "doc_1234567890"
        similarity_score:
          type: number
          description: Similarity score of the retrieved chunk
          minimum: 0.0
          maximum: 1.0
          example: 0.87
        chunk_index:
          type: integer
          description: Index of the chunk within the document
          example: 2

    HealthResponse:
      type: object
      required:
        - status
        - service
        - timestamp
      properties:
        status:
          type: string
          enum: [healthy, unhealthy]
          example: "healthy"
        service:
          type: string
          description: Name of the service
          example: "RAG Agent Service"
        timestamp:
          type: string
          format: date-time
          description: Timestamp of the health check
          example: "2025-12-26T10:00:00Z"
        dependencies:
          type: object
          description: Health status of dependent services
          properties:
            openai:
              type: string
              enum: [healthy, unhealthy]
            qdrant:
              type: string
              enum: [healthy, unhealthy]
            cohere:
              type: string
              enum: [healthy, unhealthy]

    AgentStatusResponse:
      type: object
      required:
        - status
        - total_queries
        - successful_queries
        - avg_response_time_ms
        - last_updated
      properties:
        status:
          type: string
          enum: [running, stopped, degraded]
          example: "running"
        total_queries:
          type: integer
          description: Total number of queries processed
          example: 1250
        successful_queries:
          type: integer
          description: Number of successful queries
          example: 1245
        success_rate:
          type: number
          description: Success rate as a percentage
          example: 99.6
        avg_response_time_ms:
          type: integer
          description: Average response time in milliseconds
          example: 1150
        last_updated:
          type: string
          format: date-time
          description: When the status was last updated
          example: "2025-12-26T10:00:00Z"

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
          example: "QUERY_PROCESSING_ERROR"
        message:
          type: string
          description: Human-readable error message
          example: "Error processing the query"
        details:
          type: object
          description: Additional error details (optional)