openapi: 3.0.0
info:
  title: RAG Chatbot API
  description: API for the Integrated RAG Chatbot for Physical AI & Humanoid Robotics Textbook
  version: 1.0.0
servers:
  - url: https://api.rag-chatbot.example.com/v1
    description: Production server
  - url: https://staging-api.rag-chatbot.example.com/v1
    description: Staging server

paths:
  /ingest:
    post:
      summary: Ingest textbook content for RAG
      description: Process and index textbook markdown content for retrieval
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  description: The textbook content to be ingested
                title:
                  type: string
                  description: Title of the content section
                chapter:
                  type: string
                  description: Chapter identifier
                section:
                  type: string
                  description: Section identifier
                source_file:
                  type: string
                  description: Original source file path
              required:
                - content
                - title
                - chapter
                - section
                - source_file
      responses:
        '200':
          description: Content successfully ingested and indexed
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  document_id:
                    type: string
                    example: "doc_12345"
                  chunks_processed:
                    type: integer
                    example: 5
        '400':
          description: Invalid input parameters
        '500':
          description: Internal server error during ingestion

  /chat:
    post:
      summary: Chat with the RAG system using full textbook content
      description: Submit a question and receive an answer based on the full textbook content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
                  description: The question to ask
                  maxLength: 500
                session_id:
                  type: string
                  description: Optional session identifier for context
                page_context:
                  type: string
                  description: Optional page/chapter context for the question
              required:
                - question
      responses:
        '200':
          description: Successful response from the chatbot
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    description: The chatbot's response
                  confidence_score:
                    type: number
                    format: float
                    description: Confidence score between 0 and 1
                    minimum: 0
                    maximum: 1
                  citations:
                    type: array
                    items:
                      type: object
                      properties:
                        content_id:
                          type: string
                        title:
                          type: string
                        chapter:
                          type: string
                        text_preview:
                          type: string
                  session_id:
                    type: string
                    description: The session identifier
                  response_time:
                    type: number
                    format: float
                    description: Time taken to generate response in seconds
        '400':
          description: Invalid input parameters
        '429':
          description: Rate limit exceeded
        '500':
          description: Internal server error

  /chat-selected:
    post:
      summary: Chat with the RAG system using only selected text
      description: Submit a question and receive an answer based only on user-selected text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
                  description: The question to ask
                  maxLength: 500
                selected_text:
                  type: string
                  description: The text selected by the user to answer from
                  maxLength: 2000
                session_id:
                  type: string
                  description: Optional session identifier for context
              required:
                - question
                - selected_text
      responses:
        '200':
          description: Successful response from the chatbot based on selected text
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    description: The chatbot's response
                  confidence_score:
                    type: number
                    format: float
                    description: Confidence score between 0 and 1
                    minimum: 0
                    maximum: 1
                  source_text_used:
                    type: string
                    description: The text that was used as the source for the response
                  session_id:
                    type: string
                    description: The session identifier
                  response_time:
                    type: number
                    format: float
                    description: Time taken to generate response in seconds
        '400':
          description: Invalid input parameters
        '422':
          description: Selected text is too short or insufficient for answering
        '429':
          description: Rate limit exceeded
        '500':
          description: Internal server error

components:
  schemas:
    TextbookChunk:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the content chunk
        content:
          type: string
          description: The text content of the chunk
        title:
          type: string
          description: Title of the section/chapter
        chapter:
          type: string
          description: The chapter number or identifier
        section:
          type: string
          description: The section identifier
        source_file:
          type: string
          description: Original source file path
        metadata:
          type: object
          description: Additional metadata about the content